#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.5
#  in conjunction with Tcl version 8.6
#    Nov 19, 2022 01:59:45 PM CET  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import Data
import map_edit_gui
import csv
import csv_data
import map_edit_gui_update

"""
Default settings
"""
default_map_size_x = 3
default_map_size_y = 3

map = map = Data.Map(Data.getEmptyArray(default_map_size_x,default_map_size_y))

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    global map
    
    _top1 = root
    _w1 = map_edit_gui.Toplevel1(map,_top1)

    root.mainloop()
def updateMapWithCanv(canv):
    global map
    for widget in canv.winfo_children():
        if widget["bg"] == map_edit_gui.ObstacleColour:
            map.setPosObstacle(int(widget.grid_info()['row']),int(widget.grid_info()['column']))
        else:map.setPosNoObstacle(int(widget.grid_info()['row']),int(widget.grid_info()['column']))

def genMap(canv,map):
    updateMapWithCanv(canv)
    csv_data.write(map)

def OpenMap(canv):
    map_edit_gui_update.updateCanvWithMap(canv,csv_data.read())

if __name__ == '__main__':
    map_edit_gui.start_up()




